<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['libelle_pays' => 'Aruba', 'flag' => 'https://flagcdn.com/w320/aw.png'],
            ['libelle_pays' => 'Afghanistan', 'flag' => 'https://flagcdn.com/w320/af.png'],
            ['libelle_pays' => 'Angola', 'flag' => 'https://flagcdn.com/w320/ao.png'],
            ['libelle_pays' => 'Anguilla', 'flag' => 'https://flagcdn.com/w320/ai.png'],
            ['libelle_pays' => 'Îles Åland', 'flag' => 'https://flagcdn.com/w320/ax.png'],
            ['libelle_pays' => 'Albanie', 'flag' => 'https://flagcdn.com/w320/al.png'],
            ['libelle_pays' => 'Andorre', 'flag' => 'https://flagcdn.com/w320/ad.png'],
            ['libelle_pays' => 'Émirats arabes unis', 'flag' => 'https://flagcdn.com/w320/ae.png'],
            ['libelle_pays' => 'Argentine', 'flag' => 'https://flagcdn.com/w320/ar.png'],
            ['libelle_pays' => 'Arménie', 'flag' => 'https://flagcdn.com/w320/am.png'],
            ['libelle_pays' => 'Samoa américaines', 'flag' => 'https://flagcdn.com/w320/as.png'],
            ['libelle_pays' => 'Antarctique', 'flag' => 'https://flagcdn.com/w320/aq.png'],
            ['libelle_pays' => 'Terres australes françaises', 'flag' => 'https://flagcdn.com/w320/tf.png'],
            ['libelle_pays' => 'Antigua-et-Barbuda', 'flag' => 'https://flagcdn.com/w320/ag.png'],
            ['libelle_pays' => 'Australie', 'flag' => 'https://flagcdn.com/w320/au.png'],
            ['libelle_pays' => 'Autriche', 'flag' => 'https://flagcdn.com/w320/at.png'],
            ['libelle_pays' => 'Azerbaïdjan', 'flag' => 'https://flagcdn.com/w320/az.png'],
            ['libelle_pays' => 'Burundi', 'flag' => 'https://flagcdn.com/w320/bi.png'],
            ['libelle_pays' => 'Belgique', 'flag' => 'https://flagcdn.com/w320/be.png'],
            ['libelle_pays' => 'Bénin', 'flag' => 'https://flagcdn.com/w320/bj.png'],
            ['libelle_pays' => 'Pays-Bas caribéens', 'flag' => 'https://flagcdn.com/w320/bq.png'],
            ['libelle_pays' => 'Burkina Faso', 'flag' => 'https://flagcdn.com/w320/bf.png'],
            ['libelle_pays' => 'Bangladesh', 'flag' => 'https://flagcdn.com/w320/bd.png'],
            ['libelle_pays' => 'Bulgarie', 'flag' => 'https://flagcdn.com/w320/bg.png'],
            ['libelle_pays' => 'Bahreïn', 'flag' => 'https://flagcdn.com/w320/bh.png'],
            ['libelle_pays' => 'Bahamas', 'flag' => 'https://flagcdn.com/w320/bs.png'],
            ['libelle_pays' => 'Bosnie-Herzégovine', 'flag' => 'https://flagcdn.com/w320/ba.png'],
            ['libelle_pays' => 'Saint-Barthélemy', 'flag' => 'https://flagcdn.com/w320/bl.png'],
            ['libelle_pays' => 'Biélorussie', 'flag' => 'https://flagcdn.com/w320/by.png'],
            ['libelle_pays' => 'Belize', 'flag' => 'https://flagcdn.com/w320/bz.png'],
            ['libelle_pays' => 'Bermudes', 'flag' => 'https://flagcdn.com/w320/bm.png'],
            ['libelle_pays' => 'Bolivie', 'flag' => 'https://flagcdn.com/w320/bo.png'],
            ['libelle_pays' => 'Brésil', 'flag' => 'https://flagcdn.com/w320/br.png'],
            ['libelle_pays' => 'Barbade', 'flag' => 'https://flagcdn.com/w320/bb.png'],
            ['libelle_pays' => 'Brunei', 'flag' => 'https://flagcdn.com/w320/bn.png'],
            ['libelle_pays' => 'Bhoutan', 'flag' => 'https://flagcdn.com/w320/bt.png'],
            ['libelle_pays' => 'Île Bouvet', 'flag' => 'https://flagcdn.com/w320/bv.png'],
            ['libelle_pays' => 'Botswana', 'flag' => 'https://flagcdn.com/w320/bw.png'],
            ['libelle_pays' => 'République centrafricaine', 'flag' => 'https://flagcdn.com/w320/cf.png'],
            ['libelle_pays' => 'Canada', 'flag' => 'https://flagcdn.com/w320/ca.png'],
            ['libelle_pays' => 'Îles Cocos', 'flag' => 'https://flagcdn.com/w320/cc.png'],
            ['libelle_pays' => 'Suisse', 'flag' => 'https://flagcdn.com/w320/ch.png'],
            ['libelle_pays' => 'Chili', 'flag' => 'https://flagcdn.com/w320/cl.png'],
            ['libelle_pays' => 'Chine', 'flag' => 'https://flagcdn.com/w320/cn.png'],
            ['libelle_pays' => 'Côte d’Ivoire', 'flag' => 'https://flagcdn.com/w320/ci.png'],
            ['libelle_pays' => 'Cameroun', 'flag' => 'https://flagcdn.com/w320/cm.png'],
            ['libelle_pays' => 'Congo-Kinshasa', 'flag' => 'https://flagcdn.com/w320/cd.png'],
            ['libelle_pays' => 'Congo-Brazzaville', 'flag' => 'https://flagcdn.com/w320/cg.png'],
            ['libelle_pays' => 'Îles Cook', 'flag' => 'https://flagcdn.com/w320/ck.png'],
            ['libelle_pays' => 'Colombie', 'flag' => 'https://flagcdn.com/w320/co.png'],
            ['libelle_pays' => 'Comores', 'flag' => 'https://flagcdn.com/w320/km.png'],
            ['libelle_pays' => 'Cap-Vert', 'flag' => 'https://flagcdn.com/w320/cv.png'],
            ['libelle_pays' => 'Costa Rica', 'flag' => 'https://flagcdn.com/w320/cr.png'],
            ['libelle_pays' => 'Cuba', 'flag' => 'https://flagcdn.com/w320/cu.png'],
            ['libelle_pays' => 'Curaçao', 'flag' => 'https://flagcdn.com/w320/cw.png'],
            ['libelle_pays' => 'Île Christmas', 'flag' => 'https://flagcdn.com/w320/cx.png'],
            ['libelle_pays' => 'Îles Caïmans', 'flag' => 'https://flagcdn.com/w320/ky.png'],
            ['libelle_pays' => 'Chypre', 'flag' => 'https://flagcdn.com/w320/cy.png'],
            ['libelle_pays' => 'Tchéquie', 'flag' => 'https://flagcdn.com/w320/cz.png'],
            ['libelle_pays' => 'Allemagne', 'flag' => 'https://flagcdn.com/w320/de.png'],
            ['libelle_pays' => 'Djibouti', 'flag' => 'https://flagcdn.com/w320/dj.png'],
            ['libelle_pays' => 'Dominique', 'flag' => 'https://flagcdn.com/w320/dm.png'],
            ['libelle_pays' => 'Danemark', 'flag' => 'https://flagcdn.com/w320/dk.png'],
            ['libelle_pays' => 'République dominicaine', 'flag' => 'https://flagcdn.com/w320/do.png'],
            ['libelle_pays' => 'Algérie', 'flag' => 'https://flagcdn.com/w320/dz.png'],
            ['libelle_pays' => 'Équateur', 'flag' => 'https://flagcdn.com/w320/ec.png'],
            ['libelle_pays' => 'Égypte', 'flag' => 'https://flagcdn.com/w320/eg.png'],
            ['libelle_pays' => 'Érythrée', 'flag' => 'https://flagcdn.com/w320/er.png'],
            ['libelle_pays' => 'Sahara occidental', 'flag' => 'https://flagcdn.com/w320/eh.png'],
            ['libelle_pays' => 'Espagne', 'flag' => 'https://flagcdn.com/w320/es.png'],
            ['libelle_pays' => 'Estonie', 'flag' => 'https://flagcdn.com/w320/ee.png'],
            ['libelle_pays' => 'Éthiopie', 'flag' => 'https://flagcdn.com/w320/et.png'],
            ['libelle_pays' => 'Finlande', 'flag' => 'https://flagcdn.com/w320/fi.png'],
            ['libelle_pays' => 'Fidji', 'flag' => 'https://flagcdn.com/w320/fj.png'],
            ['libelle_pays' => 'Îles Malouines', 'flag' => 'https://flagcdn.com/w320/fk.png'],
            ['libelle_pays' => 'France', 'flag' => 'https://flagcdn.com/w320/fr.png'],
            ['libelle_pays' => 'Îles Féroé', 'flag' => 'https://flagcdn.com/w320/fo.png'],
            ['libelle_pays' => 'Micronésie', 'flag' => 'https://flagcdn.com/w320/fm.png'],
            ['libelle_pays' => 'Gabon', 'flag' => 'https://flagcdn.com/w320/ga.png'],
            ['libelle_pays' => 'Royaume-Uni', 'flag' => 'https://flagcdn.com/w320/gb.png'],
            ['libelle_pays' => 'Géorgie', 'flag' => 'https://flagcdn.com/w320/ge.png'],
            ['libelle_pays' => 'Guernesey', 'flag' => 'https://flagcdn.com/w320/gg.png'],
            ['libelle_pays' => 'Ghana', 'flag' => 'https://flagcdn.com/w320/gh.png'],
            ['libelle_pays' => 'Gibraltar', 'flag' => 'https://flagcdn.com/w320/gi.png'],
            ['libelle_pays' => 'Guinée', 'flag' => 'https://flagcdn.com/w320/gn.png'],
            ['libelle_pays' => 'Guadeloupe', 'flag' => 'https://flagcdn.com/w320/gp.png'],
            ['libelle_pays' => 'Gambie', 'flag' => 'https://flagcdn.com/w320/gm.png'],
            ['libelle_pays' => 'Guinée-Bissau', 'flag' => 'https://flagcdn.com/w320/gw.png'],
            ['libelle_pays' => 'Guinée équatoriale', 'flag' => 'https://flagcdn.com/w320/gq.png'],
            ['libelle_pays' => 'Grèce', 'flag' => 'https://flagcdn.com/w320/gr.png'],
            ['libelle_pays' => 'Grenade', 'flag' => 'https://flagcdn.com/w320/gd.png'],
            ['libelle_pays' => 'Groenland', 'flag' => 'https://flagcdn.com/w320/gl.png'],
            ['libelle_pays' => 'Guatemala', 'flag' => 'https://flagcdn.com/w320/gt.png'],
            ['libelle_pays' => 'Guyane française', 'flag' => 'https://flagcdn.com/w320/gf.png'],
            ['libelle_pays' => 'Guam', 'flag' => 'https://flagcdn.com/w320/gu.png'],
            ['libelle_pays' => 'Guyana', 'flag' => 'https://flagcdn.com/w320/gy.png'],
            ['libelle_pays' => 'R.A.S. chinoise de Hong Kong', 'flag' => 'https://flagcdn.com/w320/hk.png'],
            ['libelle_pays' => 'Îles Heard-et-MacDonald', 'flag' => 'https://flagcdn.com/w320/hm.png'],
            ['libelle_pays' => 'Honduras', 'flag' => 'https://flagcdn.com/w320/hn.png'],
            ['libelle_pays' => 'Croatie', 'flag' => 'https://flagcdn.com/w320/hr.png'],
            ['libelle_pays' => 'Haïti', 'flag' => 'https://flagcdn.com/w320/ht.png'],
            ['libelle_pays' => 'Hongrie', 'flag' => 'https://flagcdn.com/w320/hu.png'],
            ['libelle_pays' => 'Indonésie', 'flag' => 'https://flagcdn.com/w320/id.png'],
            ['libelle_pays' => 'Île de Man', 'flag' => 'https://flagcdn.com/w320/im.png'],
            ['libelle_pays' => 'Inde', 'flag' => 'https://flagcdn.com/w320/in.png'],
            ['libelle_pays' => 'Territoire britannique de l’océan Indien', 'flag' => 'https://flagcdn.com/w320/io.png'],
            ['libelle_pays' => 'Irlande', 'flag' => 'https://flagcdn.com/w320/ie.png'],
            ['libelle_pays' => 'Iran', 'flag' => 'https://flagcdn.com/w320/ir.png'],
            ['libelle_pays' => 'Irak', 'flag' => 'https://flagcdn.com/w320/iq.png'],
            ['libelle_pays' => 'Islande', 'flag' => 'https://flagcdn.com/w320/is.png'],
            ['libelle_pays' => 'Israël', 'flag' => 'https://flagcdn.com/w320/il.png'],
            ['libelle_pays' => 'Italie', 'flag' => 'https://flagcdn.com/w320/it.png'],
            ['libelle_pays' => 'Jamaïque', 'flag' => 'https://flagcdn.com/w320/jm.png'],
            ['libelle_pays' => 'Jersey', 'flag' => 'https://flagcdn.com/w320/je.png'],
            ['libelle_pays' => 'Jordanie', 'flag' => 'https://flagcdn.com/w320/jo.png'],
            ['libelle_pays' => 'Japon', 'flag' => 'https://flagcdn.com/w320/jp.png'],
            ['libelle_pays' => 'Kazakhstan', 'flag' => 'https://flagcdn.com/w320/kz.png'],
            ['libelle_pays' => 'Kenya', 'flag' => 'https://flagcdn.com/w320/ke.png'],
            ['libelle_pays' => 'Kirghizstan', 'flag' => 'https://flagcdn.com/w320/kg.png'],
            ['libelle_pays' => 'Cambodge', 'flag' => 'https://flagcdn.com/w320/kh.png'],
            ['libelle_pays' => 'Kiribati', 'flag' => 'https://flagcdn.com/w320/ki.png'],
            ['libelle_pays' => 'Saint-Christophe-et-Niévès', 'flag' => 'https://flagcdn.com/w320/kn.png'],
            ['libelle_pays' => 'Corée du Sud', 'flag' => 'https://flagcdn.com/w320/kr.png'],
            ['libelle_pays' => 'Koweït', 'flag' => 'https://flagcdn.com/w320/kw.png'],
            ['libelle_pays' => 'Laos', 'flag' => 'https://flagcdn.com/w320/la.png'],
            ['libelle_pays' => 'Liban', 'flag' => 'https://flagcdn.com/w320/lb.png'],
            ['libelle_pays' => 'Liberia', 'flag' => 'https://flagcdn.com/w320/lr.png'],
            ['libelle_pays' => 'Libye', 'flag' => 'https://flagcdn.com/w320/ly.png'],
            ['libelle_pays' => 'Sainte-Lucie', 'flag' => 'https://flagcdn.com/w320/lc.png'],
            ['libelle_pays' => 'Liechtenstein', 'flag' => 'https://flagcdn.com/w320/li.png'],
            ['libelle_pays' => 'Sri Lanka', 'flag' => 'https://flagcdn.com/w320/lk.png'],
            ['libelle_pays' => 'Lesotho', 'flag' => 'https://flagcdn.com/w320/ls.png'],
            ['libelle_pays' => 'Lituanie', 'flag' => 'https://flagcdn.com/w320/lt.png'],
            ['libelle_pays' => 'Luxembourg', 'flag' => 'https://flagcdn.com/w320/lu.png'],
            ['libelle_pays' => 'Lettonie', 'flag' => 'https://flagcdn.com/w320/lv.png'],
            ['libelle_pays' => 'R.A.S. chinoise de Macao', 'flag' => 'https://flagcdn.com/w320/mo.png'],
            ['libelle_pays' => 'Saint-Martin', 'flag' => 'https://flagcdn.com/w320/mf.png'],
            ['libelle_pays' => 'Maroc', 'flag' => 'https://flagcdn.com/w320/ma.png'],
            ['libelle_pays' => 'Monaco', 'flag' => 'https://flagcdn.com/w320/mc.png'],
            ['libelle_pays' => 'Moldavie', 'flag' => 'https://flagcdn.com/w320/md.png'],
            ['libelle_pays' => 'Madagascar', 'flag' => 'https://flagcdn.com/w320/mg.png'],
            ['libelle_pays' => 'Maldives', 'flag' => 'https://flagcdn.com/w320/mv.png'],
            ['libelle_pays' => 'Mexique', 'flag' => 'https://flagcdn.com/w320/mx.png'],
            ['libelle_pays' => 'Îles Marshall', 'flag' => 'https://flagcdn.com/w320/mh.png'],
            ['libelle_pays' => 'Macédoine du Nord', 'flag' => 'https://flagcdn.com/w320/mk.png'],
            ['libelle_pays' => 'Mali', 'flag' => 'https://flagcdn.com/w320/ml.png'],
            ['libelle_pays' => 'Malte', 'flag' => 'https://flagcdn.com/w320/mt.png'],
            ['libelle_pays' => 'Myanmar (Birmanie)', 'flag' => 'https://flagcdn.com/w320/mm.png'],
            ['libelle_pays' => 'Monténégro', 'flag' => 'https://flagcdn.com/w320/me.png'],
            ['libelle_pays' => 'Mongolie', 'flag' => 'https://flagcdn.com/w320/mn.png'],
            ['libelle_pays' => 'Îles Mariannes du Nord', 'flag' => 'https://flagcdn.com/w320/mp.png'],
            ['libelle_pays' => 'Mozambique', 'flag' => 'https://flagcdn.com/w320/mz.png'],
            ['libelle_pays' => 'Mauritanie', 'flag' => 'https://flagcdn.com/w320/mr.png'],
            ['libelle_pays' => 'Montserrat', 'flag' => 'https://flagcdn.com/w320/ms.png'],
            ['libelle_pays' => 'Martinique', 'flag' => 'https://flagcdn.com/w320/mq.png'],
            ['libelle_pays' => 'Maurice', 'flag' => 'https://flagcdn.com/w320/mu.png'],
            ['libelle_pays' => 'Malawi', 'flag' => 'https://flagcdn.com/w320/mw.png'],
            ['libelle_pays' => 'Malaisie', 'flag' => 'https://flagcdn.com/w320/my.png'],
            ['libelle_pays' => 'Mayotte', 'flag' => 'https://flagcdn.com/w320/yt.png'],
            ['libelle_pays' => 'Namibie', 'flag' => 'https://flagcdn.com/w320/na.png'],
            ['libelle_pays' => 'Nouvelle-Calédonie', 'flag' => 'https://flagcdn.com/w320/nc.png'],
            ['libelle_pays' => 'Niger', 'flag' => 'https://flagcdn.com/w320/ne.png'],
            ['libelle_pays' => 'Île Norfolk', 'flag' => 'https://flagcdn.com/w320/nf.png'],
            ['libelle_pays' => 'Nigeria', 'flag' => 'https://flagcdn.com/w320/ng.png'],
            ['libelle_pays' => 'Nicaragua', 'flag' => 'https://flagcdn.com/w320/ni.png'],
            ['libelle_pays' => 'Niue', 'flag' => 'https://flagcdn.com/w320/nu.png'],
            ['libelle_pays' => 'Pays-Bas', 'flag' => 'https://flagcdn.com/w320/nl.png'],
            ['libelle_pays' => 'Norvège', 'flag' => 'https://flagcdn.com/w320/no.png'],
            ['libelle_pays' => 'Népal', 'flag' => 'https://flagcdn.com/w320/np.png'],
            ['libelle_pays' => 'Nauru', 'flag' => 'https://flagcdn.com/w320/nr.png'],
            ['libelle_pays' => 'Nouvelle-Zélande', 'flag' => 'https://flagcdn.com/w320/nz.png'],
            ['libelle_pays' => 'Oman', 'flag' => 'https://flagcdn.com/w320/om.png'],
            ['libelle_pays' => 'Pakistan', 'flag' => 'https://flagcdn.com/w320/pk.png'],
            ['libelle_pays' => 'Panama', 'flag' => 'https://flagcdn.com/w320/pa.png'],
            ['libelle_pays' => 'Îles Pitcairn', 'flag' => 'https://flagcdn.com/w320/pn.png'],
            ['libelle_pays' => 'Pérou', 'flag' => 'https://flagcdn.com/w320/pe.png'],
            ['libelle_pays' => 'Philippines', 'flag' => 'https://flagcdn.com/w320/ph.png'],
            ['libelle_pays' => 'Palaos', 'flag' => 'https://flagcdn.com/w320/pw.png'],
            ['libelle_pays' => 'Papouasie-Nouvelle-Guinée', 'flag' => 'https://flagcdn.com/w320/pg.png'],
            ['libelle_pays' => 'Pologne', 'flag' => 'https://flagcdn.com/w320/pl.png'],
            ['libelle_pays' => 'Porto Rico', 'flag' => 'https://flagcdn.com/w320/pr.png'],
            ['libelle_pays' => 'Corée du Nord', 'flag' => 'https://flagcdn.com/w320/kp.png'],
            ['libelle_pays' => 'Portugal', 'flag' => 'https://flagcdn.com/w320/pt.png'],
            ['libelle_pays' => 'Paraguay', 'flag' => 'https://flagcdn.com/w320/py.png'],
            ['libelle_pays' => 'Territoires palestiniens', 'flag' => 'https://flagcdn.com/w320/ps.png'],
            ['libelle_pays' => 'Polynésie française', 'flag' => 'https://flagcdn.com/w320/pf.png'],
            ['libelle_pays' => 'Qatar', 'flag' => 'https://flagcdn.com/w320/qa.png'],
            ['libelle_pays' => 'La Réunion', 'flag' => 'https://flagcdn.com/w320/re.png'],
            ['libelle_pays' => 'Roumanie', 'flag' => 'https://flagcdn.com/w320/ro.png'],
            ['libelle_pays' => 'Russie', 'flag' => 'https://flagcdn.com/w320/ru.png'],
            ['libelle_pays' => 'Rwanda', 'flag' => 'https://flagcdn.com/w320/rw.png'],
            ['libelle_pays' => 'Arabie saoudite', 'flag' => 'https://flagcdn.com/w320/sa.png'],
            ['libelle_pays' => 'Soudan', 'flag' => 'https://flagcdn.com/w320/sd.png'],
            ['libelle_pays' => 'Sénégal', 'flag' => 'https://flagcdn.com/w320/sn.png'],
            ['libelle_pays' => 'Singapour', 'flag' => 'https://flagcdn.com/w320/sg.png'],
            ['libelle_pays' => 'Géorgie du Sud-et-les Îles Sandwich du Sud', 'flag' => 'https://flagcdn.com/w320/gs.png'],
            ['libelle_pays' => 'Sainte-Hélène', 'flag' => 'https://flagcdn.com/w320/sh.png'],
            ['libelle_pays' => 'Svalbard et Jan Mayen', 'flag' => 'https://flagcdn.com/w320/sj.png'],
            ['libelle_pays' => 'Îles Salomon', 'flag' => 'https://flagcdn.com/w320/sb.png'],
            ['libelle_pays' => 'Sierra Leone', 'flag' => 'https://flagcdn.com/w320/sl.png'],
            ['libelle_pays' => 'Salvador', 'flag' => 'https://flagcdn.com/w320/sv.png'],
            ['libelle_pays' => 'Saint-Marin', 'flag' => 'https://flagcdn.com/w320/sm.png'],
            ['libelle_pays' => 'Somalie', 'flag' => 'https://flagcdn.com/w320/so.png'],
            ['libelle_pays' => 'Saint-Pierre-et-Miquelon', 'flag' => 'https://flagcdn.com/w320/pm.png'],
            ['libelle_pays' => 'Serbie', 'flag' => 'https://flagcdn.com/w320/rs.png'],
            ['libelle_pays' => 'Soudan du Sud', 'flag' => 'https://flagcdn.com/w320/ss.png'],
            ['libelle_pays' => 'Sao Tomé-et-Principe', 'flag' => 'https://flagcdn.com/w320/st.png'],
            ['libelle_pays' => 'Suriname', 'flag' => 'https://flagcdn.com/w320/sr.png'],
            ['libelle_pays' => 'Slovaquie', 'flag' => 'https://flagcdn.com/w320/sk.png'],
            ['libelle_pays' => 'Slovénie', 'flag' => 'https://flagcdn.com/w320/si.png'],
            ['libelle_pays' => 'Suède', 'flag' => 'https://flagcdn.com/w320/se.png'],
            ['libelle_pays' => 'Eswatini', 'flag' => 'https://flagcdn.com/w320/sz.png'],
            ['libelle_pays' => 'Saint-Martin (partie néerlandaise)', 'flag' => 'https://flagcdn.com/w320/sx.png'],
            ['libelle_pays' => 'Seychelles', 'flag' => 'https://flagcdn.com/w320/sc.png'],
            ['libelle_pays' => 'Syrie', 'flag' => 'https://flagcdn.com/w320/sy.png'],
            ['libelle_pays' => 'Îles Turques-et-Caïques', 'flag' => 'https://flagcdn.com/w320/tc.png'],
            ['libelle_pays' => 'Tchad', 'flag' => 'https://flagcdn.com/w320/td.png'],
            ['libelle_pays' => 'Togo', 'flag' => 'https://flagcdn.com/w320/tg.png'],
            ['libelle_pays' => 'Thaïlande', 'flag' => 'https://flagcdn.com/w320/th.png'],
            ['libelle_pays' => 'Tadjikistan', 'flag' => 'https://flagcdn.com/w320/tj.png'],
            ['libelle_pays' => 'Tokelau', 'flag' => 'https://flagcdn.com/w320/tk.png'],
            ['libelle_pays' => 'Turkménistan', 'flag' => 'https://flagcdn.com/w320/tm.png'],
            ['libelle_pays' => 'Timor oriental', 'flag' => 'https://flagcdn.com/w320/tl.png'],
            ['libelle_pays' => 'Tonga', 'flag' => 'https://flagcdn.com/w320/to.png'],
            ['libelle_pays' => 'Trinité-et-Tobago', 'flag' => 'https://flagcdn.com/w320/tt.png'],
            ['libelle_pays' => 'Tunisie', 'flag' => 'https://flagcdn.com/w320/tn.png'],
            ['libelle_pays' => 'Turquie', 'flag' => 'https://flagcdn.com/w320/tr.png'],
            ['libelle_pays' => 'Tuvalu', 'flag' => 'https://flagcdn.com/w320/tv.png'],
            ['libelle_pays' => 'Taïwan', 'flag' => 'https://flagcdn.com/w320/tw.png'],
            ['libelle_pays' => 'Tanzanie', 'flag' => 'https://flagcdn.com/w320/tz.png'],
            ['libelle_pays' => 'Ouganda', 'flag' => 'https://flagcdn.com/w320/ug.png'],
            ['libelle_pays' => 'Ukraine', 'flag' => 'https://flagcdn.com/w320/ua.png'],
            ['libelle_pays' => 'Îles mineures éloignées des États-Unis', 'flag' => 'https://flagcdn.com/w320/um.png'],
            ['libelle_pays' => 'Uruguay', 'flag' => 'https://flagcdn.com/w320/uy.png'],
            ['libelle_pays' => 'États-Unis', 'flag' => 'https://flagcdn.com/w320/us.png'],
            ['libelle_pays' => 'Ouzbékistan', 'flag' => 'https://flagcdn.com/w320/uz.png'],
            ['libelle_pays' => 'État de la Cité du Vatican', 'flag' => 'https://flagcdn.com/w320/va.png'],
            ['libelle_pays' => 'Saint-Vincent-et-les Grenadines', 'flag' => 'https://flagcdn.com/w320/vc.png'],
            ['libelle_pays' => 'Venezuela', 'flag' => 'https://flagcdn.com/w320/ve.png'],
            ['libelle_pays' => 'Îles Vierges britanniques', 'flag' => 'https://flagcdn.com/w320/vg.png'],
            ['libelle_pays' => 'Îles Vierges des États-Unis', 'flag' => 'https://flagcdn.com/w320/vi.png'],
            ['libelle_pays' => 'Viêt Nam', 'flag' => 'https://flagcdn.com/w320/vn.png'],
            ['libelle_pays' => 'Vanuatu', 'flag' => 'https://flagcdn.com/w320/vu.png'],
            ['libelle_pays' => 'Wallis-et-Futuna', 'flag' => 'https://flagcdn.com/w320/wf.png'],
            ['libelle_pays' => 'Samoa', 'flag' => 'https://flagcdn.com/w320/ws.png'],
            ['libelle_pays' => 'Yémen', 'flag' => 'https://flagcdn.com/w320/ye.png'],
            ['libelle_pays' => 'Afrique du Sud', 'flag' => 'https://flagcdn.com/w320/za.png'],
            ['libelle_pays' => 'Zambie', 'flag' => 'https://flagcdn.com/w320/zm.png'],
            ['libelle_pays' => 'Zimbabwe', 'flag' => 'https://flagcdn.com/w320/zw.png'],
        ];

        DB::table('countries')->insert($countries);
    }
}
